# Generated by Django 2.1.2 on 2018-11-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(to='kitchen.Ingredient'),
        ),
    ]
